normal_config:
 description: "Config Description. Type Anything Here."
 path: "./accounts/ajiperuprovo/config.yml"
unfollow_config:
 description: "Config 2 Description. Type Anything Here."
 path: "./accounts/ajiperuprovo/config1.yml"